dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Apply Terraform test configs in mockstack
      install:
        - make docker-compose/install
        - make mockstack/up
      script: make mockstack/pytest
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-config
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [TARDIGRADE-CONFIG v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-config/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: YnOO5NhYobmrjRCbxzbZ9iZPE6tM12wVnCh0GKPlmOc5IIWpvhq+f/+MNYjqxDSVqCCY1/CAU89SL4JMCJgZ0CLsIWeLURKnVUasRlJDgiN3HHhoc1UJBW31tMoNOyRow7KRq6tSys/01f7TynOhLIC7Qu2HmzmjncvGqoOdDNQ5LztKhaiQoyi03EjcGJAHZjX7uaSNP0xPxoNiHhvpl4K9QWZR08LMn+OudkuV+MRi5pCVFImwtqyANp1QjKsp3syvuuLB6UTk6uWlXFX1nRga00CdpDPnIbXyWhwkAg2SvlVDbld3PrLaMEn9bw+SWxFVePmBEBFbkxBIBOg1xIg3AiRJ2BdVqKsdzqaDeynjt3Bd3yiTRCaQ1Ak+8FPysRlMwm8AqnB+LKbTaTEjtbGRDLmbgIB9RKyOXyC/UcXvj9BI0fYnNEETscCbGrRbHz75jHYrQTzhkDT3MTfxxWF47zTxThTqE5ZLkmR7FQz3QwS1VWm1BWv5kA6jLSZjkB4ht1VraifSQ56P9VV5r7WOtHjRzwdfsZsb+m3Kw6fqKkTGi405Pm96bJINmDu4yEKhNfJNGFi+rTJMPZo1wWqXB9j1zNsitz39WoLEX4D51INGY745SCjMdKfR/+xnMDVIDpyscDpevdsHIW3LcRdKI/2yX78Zm3mZ1yS3gwo=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-config
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
